function plot_comparison(sol1, sol2, fn, params, names)
        %plot_comparison        Compare two voltage dynamics generated by the same or similar parameters and save animation to fn
        %
        % Usage:
        %                       plot_comparison(sol1, sol2, fn, params)
        %
        % Input:
        %                       sol1 = solution output from retinal2D.m or similar
        %                       sol2 = solution output from retinal2D.m
        %                       filename = save plot to this file
        %                       params = output from parameters() used to generate solution being plotted
	%			names = (optional, default = {'Sol 1', 'Sol 2'}) names of each solution for plot
        %
        % Examples:
        %                       params = parameters('ml_sahp', 'homog', [0:.1:1], 64, 'exponential');
        %                       sol1 = retinal2D_split(params);
	%			params.modelps(17) = 10;
	%			sol2 = retinal2D_split(params);
        %                       plot_comparison(sol1, sol2, './tests/test_plot_comparison.eps', params, {'Original','Set param 17 to 10'});
        if (nargin < 4)
                throw(MException('Argin:MoreExpected', 'More input arguments expected'));
        elseif (nargin < 5)
                names = {'sol 1','sol 2'};
        end
	
        sol{1} = sol1{1}; sol{2} = sol2{1}; sol{3} = sol1{1}-sol2{1};
        zaxes = {[-90 30],[-90 30],[-2 2]};
        indices = {1 2 3};
        params.names = {names{:}, 'difference'};
        plotmultisol(sol, fn, params, zaxes, indices, 1);

end

