%load('./simdata/bernoulli_long_sim_D_0_005.mat')
fn = './worksheets/finding_realistic_waves/bernoulli_long_sims_plots/bernoulli_long_sim_D_0_005_iwis.eps';
%minsize = 5;
%threshold = -30;
%compute_stats('./simdata/bernoulli_long_sim_D_0_005.mat', ['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], minsize, threshold);
%plotstats(['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], ['./worksheets/finding_realistic_waves/bernoulli_long_sims_plots/bernoulli_long_sim_D_0_005_thr_' num2str(threshold) '_minsize_' num2str(minsize)]);
%minsize = 10;
%threshold = -30;
%compute_stats('./simdata/bernoulli_long_sim_D_0_005.mat', ['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], minsize, threshold);
%plotstats(['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], ['./worksheets/finding_realistic_waves/bernoulli_long_sims_plots/bernoulli_long_sim_D_0_005_thr_' num2str(threshold) '_minsize_' num2str(minsize)]);
%minsize = 5;
%threshold = 0;
%compute_stats('./simdata/bernoulli_long_sim_D_0_005.mat', ['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], minsize, threshold);
%plotstats(['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], ['./worksheets/finding_realistic_waves/bernoulli_long_sims_plots/bernoulli_long_sim_D_0_005_thr_' num2str(threshold) '_minsize_' num2str(minsize)]);
%minsize = 10;
%threshold = 0;
%compute_stats('./simdata/bernoulli_long_sim_D_0_005.mat', ['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], minsize, threshold);
%plotstats(['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], ['./worksheets/finding_realistic_waves/bernoulli_long_sims_plots/bernoulli_long_sim_D_0_005_thr_' num2str(threshold) '_minsize_' num2str(minsize)]);
%minsize = 20;
%threshold = 0;
%compute_stats('./simdata/bernoulli_long_sim_D_0_005.mat', ['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], minsize, threshold);
%plotstats(['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], ['./worksheets/finding_realistic_waves/bernoulli_long_sims_plots/bernoulli_long_sim_D_0_005_thr_' num2str(threshold) '_minsize_' num2str(minsize)]);
minsize = 40; threshold = -50;
compute_stats('./simdata/bernoulli_long_sim_D_0_005.mat', ['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], minsize, threshold);
plotstats(['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], ['./worksheets/finding_realistic_waves/bernoulli_long_sims_plots/bernoulli_long_sim_D_0_005_thr_' num2str(threshold) '_minsize_' num2str(minsize)]);
minsize = 30; threshold = -50;
compute_stats('./simdata/bernoulli_long_sim_D_0_005.mat', ['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], minsize, threshold);
plotstats(['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], ['./worksheets/finding_realistic_waves/bernoulli_long_sims_plots/bernoulli_long_sim_D_0_005_thr_' num2str(threshold) '_minsize_' num2str(minsize)]);
minsize = 20; threshold = -50;
compute_stats('./simdata/bernoulli_long_sim_D_0_005.mat', ['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], minsize, threshold);
plotstats(['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], ['./worksheets/finding_realistic_waves/bernoulli_long_sims_plots/bernoulli_long_sim_D_0_005_thr_' num2str(threshold) '_minsize_' num2str(minsize)]);
minsize = 10; threshold = -50;
compute_stats('./simdata/bernoulli_long_sim_D_0_005.mat', ['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], minsize, threshold);
plotstats(['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], ['./worksheets/finding_realistic_waves/bernoulli_long_sims_plots/bernoulli_long_sim_D_0_005_thr_' num2str(threshold) '_minsize_' num2str(minsize)]);
minsize = 5; threshold = -50;
compute_stats('./simdata/bernoulli_long_sim_D_0_005.mat', ['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], minsize, threshold);
plotstats(['./simdata/bernoulli_long_sim_D_0_005_stats_thr_' num2str(threshold) '_minsize_' num2str(minsize) '.mat'], ['./worksheets/finding_realistic_waves/bernoulli_long_sims_plots/bernoulli_long_sim_D_0_005_thr_' num2str(threshold) '_minsize_' num2str(minsize)]);
